import { Command } from "@oclif/core";
import { readFileSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";
import { REPO_ROOT, stripHeader } from "../../lib/shared/repo/agents-header.js";

const SOURCE = join(REPO_ROOT, "system/.ai/AGENTS.md");

// Generated copies of the global instructions. Both receive the same body; the
// header is per-target so the precedence chain names the right file. Each is
// symlinked to a tool's live config (~/.claude/CLAUDE.md, ~/.codex/AGENTS.md).
// Owned by this command — `agents-header` skips `.dot-codex` so it does not fight
// this header.
const TARGETS = ["system/.dot-claude/CLAUDE.md", "system/.dot-codex/AGENTS.md"];

const SEPARATOR = "\n\n---\n\n";

// Keep the standard `AGENTS.md` precedence header, expanded with an
// auto-generated / do-not-edit note. Per-target so the chain names the right file.
function generatedHeader(targetRelativePath: string): string {
  return [
    "> **`AGENTS.md` Instruction Precedence (DO NOT EDIT)**",
    ">",
    "> Hierarchical and additive — apply this file plus all parent `AGENTS.md` files up to repo root. Most specific wins on conflict.",
    ">",
    `> **Chain:** \`${targetRelativePath}\` _(this file)_ > \`AGENTS.md\` _(root)_`,
    ">",
    "> _Auto-generated from `system/.ai/AGENTS.md` by `brain repo sync-instructions`. Do not edit this file — edit the source and re-run the sync (or `npm run build`)._",
  ].join("\n");
}

export function main(): number {
  let body: string;
  try {
    // Defensive strip in case a precedence header ever lands on the source.
    body = stripHeader(readFileSync(SOURCE, "utf8")).trimStart();
  } catch {
    process.stderr.write(`sync-instructions: source not found: ${relative(REPO_ROOT, SOURCE)}\n`);
    return 1;
  }

  process.stdout.write(`sync-instructions: from ${relative(REPO_ROOT, SOURCE)}\n`);

  for (const target of TARGETS) {
    const generated = `${generatedHeader(target)}${SEPARATOR}${body}`;
    writeFileSync(join(REPO_ROOT, target), generated, "utf8");
    process.stdout.write(`  → ${target}\n`);
  }

  process.stdout.write("sync-instructions: done ✓\n");
  return 0;
}

export default class RepoSyncInstructions extends Command {
  static description = "Sync the global instructions from system/.ai/AGENTS.md into the Claude and Codex config roots";

  async run(): Promise<void> {
    const exitCode = main();
    if (exitCode !== 0) {
      this.exit(exitCode);
    }
  }
}
