import { Command } from "@oclif/core";
import { writeFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { collectAgentsFiles, REPO_ROOT, runAgentsMdHeader } from "../../lib/shared/repo/agents-header.js";

const IGNORED_DIRECTORIES = new Set([
  ".git",
  "node_modules",
  "dist",
  ".next",
  "out",
  "coverage",
  "build",
  "system"
]);

const CLAUDE_MD_CONTENT = [
  "# USE @AGENTS.md (`AGENTS.md`)",
  "",
  "* USE @AGENTS.md (`AGENTS.md`).",
  "* AGENTS.md documents are hierarchical and additive: apply the closest `AGENTS.md` to the file(s) you are editing plus all parent `AGENTS.md` files up to the repo root.",
  "* On conflicts, the most specific document wins: **file/dir-level > subfolder-level > repo root**.",
  "",
  "_This file is auto-generated by `brain repo sync-ai`. Do not edit — edit `AGENTS.md` instead._",
  ""
].join("\n");

function syncAgentsToClaudeMd(agentsFiles: string[]): number {
  let writtenCount = 0;

  for (const agentsPath of agentsFiles) {
    const claudePath = join(dirname(agentsPath), "CLAUDE.md");
    writeFileSync(claudePath, CLAUDE_MD_CONTENT, "utf8");
    writtenCount += 1;
  }

  return writtenCount;
}

export function main(_argv: string[] = []): number {
  void _argv;

  process.stdout.write("sync-ai: AGENTS.md precedence headers\n");
  runAgentsMdHeader();
  process.stdout.write("\n");

  process.stdout.write("sync-ai: AGENTS.md → CLAUDE.md generation\n");
  const agentsFiles = collectAgentsFiles(REPO_ROOT).filter((agentsPath) => {
    const relativePath = relative(REPO_ROOT, agentsPath);
    return !relativePath.split("/").some((segment) => IGNORED_DIRECTORIES.has(segment));
  });
  const generatedCount = syncAgentsToClaudeMd(agentsFiles);
  process.stdout.write(`  → ${generatedCount} CLAUDE.md file(s) generated from AGENTS.md\n\n`);
  process.stdout.write("sync-ai: done ✓\n");
  return 0;
}

export default class RepoSyncAi extends Command {
  static description = "Sync AI config files and regenerate CLAUDE.md stubs";

  async run(): Promise<void> {
    const exitCode = main();
    if (exitCode !== 0) {
      this.exit(exitCode);
    }
  }
}
